Import('*')


SimObject('CodeletInterface.py', sim_objects=['CodeletInterface'])
SimObject('SU.py', sim_objects=['SU'])

Source('codelet_interface.cc')
Source('su.cc')

Source('../../../src/codelet/SCMUlate/src/modules/control_store.cpp')
Source('../../../src/codelet/SCMUlate/src/modules/fetch_decode.cpp')
Source('../../../src/codelet/SCMUlate/src/modules/ilp_controller.cpp')
Source('../../../src/codelet/SCMUlate/src/modules/instruction_mem.cpp')
Source('../../../src/codelet/SCMUlate/src/modules/registers.cpp')
Source('../../../src/codelet/SCMUlate/src/modules/timers_counters.cpp')
Source('../../../src/codelet/SCMUlate/src/modules/memory_interface.cpp')
Source('../../../src/codelet/SCMUlate/src/modules/executor.cpp')
Source('../../../src/codelet/SCMUlate/src/common/instructions.cpp')
Source('../../../src/codelet/SCMUlate/src/common/stringHelper.cpp')
Source('../../../src/codelet/SCMUlate/src/codelet_model/codelet.cpp')

DebugFlag('CodeletInterface')
DebugFlag('CodeletInterfaceQueue')
DebugFlag('CodeletInterfaceCod')
DebugFlag('SU')
DebugFlag('SUCod')
DebugFlag('SUSCM')
DebugFlag('SULoader')
DebugFlag('SUMem')